### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by xarling** [ryankennedy/swagger-jaxrs-doclet#14]
When using your great tool I'm experiencing a problem, which results in the following stack trace while building my project using maven:

[ERROR] Exit code: 1 - javadoc: error - In doclet class com.yammer.dropwizard.apidocs.ServiceDoclet,  method start has thrown an exception java.lang.reflect.
InvocationTargetException
[ERROR] java.lang.StackOverflowError
[ERROR] at java.lang.StringBuffer.<init>(StringBuffer.java:79)
[ERROR] at com.sun.tools.javadoc.ClassDocImpl.classToString(ClassDocImpl.java:358)
[ERROR] at com.sun.tools.javadoc.ClassDocImpl.toString(ClassDocImpl.java:332)
[ERROR] at java.lang.String.valueOf(String.java:2826)
[ERROR] at java.io.PrintStream.println(PrintStream.java:771)
[ERROR] at com.yammer.dropwizard.apidocs.ServiceDoclet.parseModels(ServiceDoclet.java:311)

I think this is caused by the parseModel addition, which tries to parse our @Context final HttpServletRequest argument at line 311 of the ServiceDoclet. 

A HttpServletRequest has a HttpSession, which has a HttpSessionContext which has a HttpSession and so on. Recursion will never stop, which results in a StackOverflowError.

**Comment by ESPNMichaelKidd** [comment]
There's a method shouldIncludeParameter(Parameter parameter) around line 327 in the servicedoclet class that likely needs to be improved, in order to stop trying to parse objects which should not be parsed...  Pull request / issue #12 looks like it would take care of this.

**Comment by jplock** [comment]
Yea I'm running into this as well, I think due to using @Auth

**Comment by ryankennedy** [comment]
Confirmed that @Auth is not causing a StackOverflow for me, either.
