### ISSUE TITLE
Java 1.6 support

### ISSUE THREAD

**Issue by lsheng** [ryankennedy/swagger-jaxrs-doclet#23]
Nice work!

I've been playing with it, and it seems to do "right" thing with regards to generating swagger specs for the swagger ui.  Unfortunately we're a Java 1.6 shop, and it looks like you've removed support for this as of https://github.com/ryankennedy/swagger-jaxrs-doclet/commit/20ba71053f13add57b74b30c1e851a7a9ff2fe8d .  It appears that it's not that much work to getting it working under 1.6(really just using explicit classes instead of <>). Would you rather me fork this kind of work, or to send a pull request for getting it working under there again.

**Comment by ESPNMichaelKidd** [comment]
based on the referenced commit, if you can get building in 1.6 and 1.7, I'm guessing a pull request would be welcomed.
