### ISSUE TITLE
Is it just me?

### ISSUE THREAD

**Issue by dgershman** [ryankennedy/swagger-jaxrs-doclet#26]
Is this project not in any maven repository?  I can't seem to get it.  Do I have to compile and manually add?

**Comment by ryankennedy** [comment]
It's in the sonatype OSS snapshot repository. I haven't cut a full release yet, so there isn't a release version yet.

https://issues.sonatype.org/browse/OSSRH-6057
https://oss.sonatype.org/content/groups/public/com/hypnoticocelot/

**Comment by dgershman** [comment]
thanks  :tada:
