### ISSUE TITLE
Recommend adding link to Carma Public Version

### ISSUE THREAD

**Issue by plessbd** [ryankennedy/swagger-jaxrs-doclet#80]
I noticed that this has been pretty stagnate on the development side.  We recently switched to https://github.com/Carma-Public/swagger-jaxrs-doclet they seem to be doing active development.

Just thought it would help others that have stumbled here to hand the torch to them.

**Comment by iamcrunch** [comment]
Bump.  +1.  Love and happiness.  Thank you.

**Comment by ryankennedy** [comment]
Done…

https://github.com/ryankennedy/swagger-jaxrs-doclet/commit/e4bc8c8044a8728f14998351b0f98e16b8822fe5
